### ISSUE TITLE
Add config option to solely disable kelp growing from Unloaded Activity

### ISSUE THREAD

**Issue by RobertHDPotatoes** [InZan17/Unloaded-Activity-Fabric#19]
Hello, I was wondering if it would be possible to get a config option to disable solely kelp from being impacted by Unloaded activity, as a common form of automatic kelp farm breaks from rapid unloaded activity growth. If you could, that would be awesome. And thanks for the awesome mod!

**Comment by InZan123** [comment]
I'll do this for the next update since I don't feel like this is a big enough change for an update. 
The reason kelp and glow berries have the same option is because they share the same logic for growing. In the meantime you could turn growPlantStems off and sacrifice the growth of glow berries.
Sorry for the inconvenience!

**Comment by RobertHDPotatoes** [comment]
Oh, I didn't realize that growPlantStems only affects glow berries as well, that's actually fine for my purposes. Thanks!

**Comment by InZan17** [comment]
I have made separate options for kelp and glow berries now. That means that the growPlantStems option is gone and you will have to disable growKelp if you wanna disable kelp from growing again.
